#!/usr/bin/env python3
"""Builds Vita3K's static assets into the core: every file of data/ and
vita3k/shaders-builtin/, as byte arrays and a table the driver grafts into
the machine's filesystem (memfs) at /chimera/assets. Both flavours link the
same file, so both hold the same bytes.

usage: gen-assets.py <extern/vita3k> <out.cpp>
"""
import os
import sys

src, out = sys.argv[1], sys.argv[2]
roots = [('data', os.path.join(src, 'data')),
         ('shaders-builtin', os.path.join(src, 'vita3k', 'shaders-builtin'))]
files = []
for name, root in roots:
    for dirpath, _, names in os.walk(root):
        for n in names:
            full = os.path.join(dirpath, n)
            files.append((name + '/' + os.path.relpath(full, root).replace(os.sep, '/'), full))
files.sort()

lines = ['// GENERATED by waterbox/gen-assets.py - do not edit.',
         '#include "assets.h"', '', 'namespace {']
for i, (_, full) in enumerate(files):
    data = open(full, 'rb').read()
    body = ','.join(str(b) for b in data)
    lines.append('const unsigned char a%d[] = {%s%s};' % (i, body, '' if data else '0'))
lines.append('} // namespace')
lines.append('')
lines.append('const chimera_vita3k::Asset chimera_vita3k::assets[] = {')
for i, (rel, full) in enumerate(files):
    lines.append('    { "%s", a%d, %d },' % (rel, i, os.path.getsize(full)))
lines.append('};')
lines.append('const size_t chimera_vita3k::asset_count = %d;' % len(files))
open(out, 'w').write('\n'.join(lines) + '\n')
print('%d assets, %d bytes' % (len(files), sum(os.path.getsize(f) for _, f in files)))
