// Vita3K's static assets, built into the core (generated by gen-assets.py).
// SPDX-License-Identifier: MIT
#pragma once

#include <cstddef>

namespace chimera_vita3k {
struct Asset {
    const char *path; // relative to /chimera/assets
    const unsigned char *data;
    size_t size;
};
extern const Asset assets[];
extern const size_t asset_count;
} // namespace chimera_vita3k
